#ifndef LEDS_H_INCLUDED
#define LEDS_H_INCLUDED

int LED_FIRE = 0;
int LED_FIRE_A_RED = 1;
int LED_FIRE_A_GREEN = 2;
int LED_FIRE_B_RED = 3;
int LED_FIRE_B_GREEN = 4;
int LED_FIRE_D_RED = 5;
int LED_FIRE_D_GREEN = 6;
int LED_FIRE_E_RED = 7;
int LED_FIRE_E_GREEN = 8;
int LED_TOGGLE_1_2_RED = 9;
int LED_TOGGLE_1_2_GREEN = 10;
int LED_TOGGLE_3_4_RED = 11;
int LED_TOGGLE_3_4_GREEN = 12;
int LED_TOGGLE_5_6_RED = 13;
int LED_TOGGLE_5_6_GREEN = 14;
int LED_POV_2_RED = 15;
int LED_POV_2_GREEN = 16;
int LED_CLUTCH_RED = 17;
int LED_CLUTCH_GREEN = 18;
int LED_THROTTLE = 19;
int MFD_STRING_TOP = 0;
int MFD_STRING_MIDDLE = 1;
int MFD_STRING_BOTTOM = 2;


int LED_FIRE_A= 1;
int LED_FIRE_B = 3;
int LED_FIRE_D = 5;
int LED_FIRE_E = 7;
int LED_TOGGLE_1_2 = 9;
int LED_TOGGLE_3_4 = 11;
int LED_TOGGLE_5_6 = 13;
int LED_POV_2 = 15;
int LED_CLUTCH = 17;

#endif // LEDS_H_INCLUDED
